<?php
/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */


require_once ( get_template_directory() . '/functions/admin-config.php' );
require_once ( get_template_directory() . '/includes/functions.php' );
require_once ( get_template_directory() . '/includes/hooks.php' );
require_once ( get_template_directory() . '/includes/strap-extras.php' );
require_once ( get_template_directory() . '/includes/plugin-activation.php' );

if ( ! function_exists('bi_option') ) {
	function bi_option($id, $fallback = false, $param = false) {
		global $bi_option;
		if ( $fallback == false ) $fallback = '';
		$output = ( isset($bi_option[$id]) && $bi_option[$id] !== '' ) ? $bi_option[$id] : $fallback;
		if ( !empty($bi_option[$id]) && $param ) {
			$output = $bi_option[$id][$param];
		}
		return $output;
	}
}

add_theme_support( 'custom-background');

require_once( get_template_directory() .'/functions/custom-css.php' );
require_once( get_template_directory() .'/functions/tracking.php' );

// Functions needed for admin
require_once( get_template_directory() .'/functions/post-types/post-type-helpers.php' );
require_once( get_template_directory() .'/functions/post-types/register-post-types.php' );
require_once( get_template_directory() .'/functions/post-types/register-taxonomies.php' );

require_once('wp-updates-theme.php');
new WPUpdatesThemeUpdater_883( 'http://wp-updates.com/api/2/theme', basename( get_template_directory() ) );